test:
  workers:
    type: local
    number: 5
  rounds:
    - label: init
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 1000
      workload:
        module: benchmarks/samples/fabric/marbles/init.js