test:
  workers:
    type: local
    number: 5
  rounds:
    - label: init
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: benchmarks/samples/fabric/marbles/init.js
    - label: query
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts:
          tps: 19
      workload:
        module: benchmarks/samples/fabric/marbles/query.js
